### PR TITLE
Add myself as a moderator

### PR DESCRIPTION
**Pull request by mathiasbynens**
Can haz edit access?

### CODE REVIEW

**Comment by caitp** [comment]
if you get edit access, feel free to fix up all the horrible typos and formatting errors in my posts =)

**Comment by mathiasbynens** [comment]
@caitp Or maybe I should just add your email address to this patch? :)

**Comment by ForbesLindesay** [comment]
Sorry, totally missed this

**Comment by ForbesLindesay** [comment]
Will be pushing a new version this weekend

**Comment by mathiasbynens** [comment]
Thanks, @ForbesLindesay! Much appreciated.

**Pull request merged**
